name: Deploy static content to Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:

  deploy:

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          VITE_ANALYTICS_DEBUG: ${{ vars.ANALYTICS_DEBUG }}
          VITE_ANALYTICS_PROVIDER: ${{ vars.ANALYTICS_PROVIDER }}
          VITE_GTM_ID: ${{ vars.GTM_ID }}

          VITE_REPO_OWNER: ${{ github.repository_owner }}
          VITE_REPO_ROCOCO: ${{ vars.REPO_ROCOCO }}
          VITE_REPO_BANK: ${{ vars.REPO_BANK }}
          VITE_REPO_AE: ${{ vars.REPO_ROCOCO }}
          VITE_REPO_AE_PY: ${{ vars.REPO_ROCOCO }}
          VITE_REPO_RESUME: ${{ github.event.repository.name }}

          VITE_ROCOCO_REPORT_EXAMPLE: ${{ vars.ROCOCO_REPORT_EXAMPLE }}
          VITE_BANK_REPORT_EXAMPLE: ${{ vars.BANK_REPORT_EXAMPLE }}
          VITE_AE_REPORT_EXAMPLE: ${{ vars.AE_REPORT_EXAMPLE }}
          VITE_AE_PY_REPORT_EXAMPLE: ${{ vars.AE_PY_REPORT_EXAMPLE }}
          VITE_SOCIAL_TELEGRAM: ${{ vars.SOCIAL_TELEGRAM }}

          VITE_SOCIAL_LINKEDIN: ${{ vars.SOCIAL_LINKEDIN }}
          VITE_SOCIAL_EMAIL: ${{ vars.SOCIAL_EMAIL }}

          VITE_DOWNLOAD_CV_PROVIDER: ${{ vars.DOWNLOAD_CV_PROVIDER }}
          VITE_CV_URL_GOOGLE_EN: ${{ vars.CV_URL_GOOGLE_EN }}
          VITE_CV_URL_GOOGLE_RU: ${{ vars.CV_URL_GOOGLE_RU }}

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
        with:
          token: '${{ github.token }}'
